clf
hold on;

iq = [180, 120, 40];
bimboFactor = [0, 0.4, 1];
%plot(iq, bimboFactor);

bimboFactor = [0, 0.4, 0.8, 1];
influence = [-0.2, 0.0, 0.5, 0.6];
%plot(bimboFactor, influence);

iqLoss = iq/20;
iqLoss = [6, 3, 1];
plot(iq, iqLoss);

%bimboFactor = [0 100 200 4000 10000];
%lust = linspace(0, 1, 100);
%bimbo = linspace(0, 1, 100);
%lustResistanceFactor = 1.5-(hornyness.^bimboFactor);

syms lustRes(lust, bimbo);
%lustRes(lust, bimbo) = 3.5*(1/((bimbo*lust).^((bimbo+40)/1000)))-3.4;
lustRes(lust, bimbo) = ((1+0.3*(1-lust)-0.8*bimbo).*(1-0.1*lust+bimbo*0.5)-0.25);

%ezsurf(lustRes, [0, 1]);

%%
title('Bimbo',...
    'FontUnits','points',...
    'Interpreter', 'latex',...
    'FontWeight','bold',...
    'FontSize',18,...
    'FontName','Times')
legend({'Bimbo Factor'},...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',12,...
    'FontName','Times',...
    'Location','NorthEast')
ylabel({'Bimbo Factor'},...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
xlabel('IQ',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
axis([0,180,0,1])
set(gca,...
    'FontSize',14);

%%
clf
hold on

iq = linspace(0, 180, 100);
bimboFactor = (180-iq)/140;
plot(iq, bimboFactor);


vertLine1 = linspace(0, 1, 100);
horLine1 = linspace(0, 180, 100);

minIq = ones(100)*40;
plot (minIq, vertLine1);
medIq = ones(100)*110;
plot(medIq, vertLine1);
startFactor = ones(100)*0.5;
plot(horLine1, startFactor);

title('Bimbo',...
    'FontUnits','points',...
    'Interpreter', 'latex',...
    'FontWeight','bold',...
    'FontSize',18,...
    'FontName','Times')
legend({'Bimbo Factor'},...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',12,...
    'FontName','Times',...
    'Location','NorthEast')
ylabel({'Different things'},...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
xlabel('IQ',...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
axis([0,180,0,1])
set(gca,...
    'FontSize',14);
